;; mugu-org-utils --- Summary
;;; -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:
;;; Package --- Summary
;;; provide reusable function related to org
;;; Commentary:
;;; Almost every function in this package expects an HEADLINE argument which
;;; should be an org-element object generated from `org-element-parse-buffer'. A
;;; local element obtained by `org-element-at-point' will not work as it doesn't
;;; have :parent property or children.
;;;  All headline generated by functions of this package are global and should
;;;  be accepted by every functions here.

;;; Code:

;; * Require
(require 'dash)

(defun mugu-orgu-get-last-buffer-name ()
  "Return the name of the last visited org buffer.
If no org buffer was visited return scratch"
  (--first (string-match-p ".*.org$" it)
           (--map (buffer-name it) (buffer-list))))

(provide 'mugu-org-utils)
;;; mugu-org-utils.el ends here
